_wandb:
    value:
        cli_version: 0.26.1
        e:
            8pmiw73fjm4ea6g4q6diipip54xbvswt:
                codePath: ReinforcementLearning/Vectorized/DoubleDQN/MountainCar/train.py
                codePathLocal: train.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "471107227648"
                        used: "225306775552"
                email: shuvrajeet17@gmail.com
                executable: /home/shuvrajeet/miniconda3/envs/research/bin/python3
                git:
                    commit: 65630d62e3426d431bf4b36cae3c753235d158c6
                    remote: https://github.com/TheUnsolvedDev/TensorflowAI.git
                gpu: NVIDIA GeForce RTX 4060 Ti
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-c311fd85-006e-6c98-235d-4ba76959797b
                    - architecture: Ada
                      cudaCores: 4352
                      memoryTotal: "17175674880"
                      name: NVIDIA GeForce RTX 4060 Ti
                      uuid: GPU-db275ced-8c17-b896-ad0a-a9528f32efbc
                host: desktop
                memory:
                    total: "134955548672"
                os: Linux-6.12.77-1-MANJARO-x86_64-with-glibc2.43
                program: /home/shuvrajeet/Documents/TensorflowAI/ReinforcementLearning/Vectorized/DoubleDQN/MountainCar/train.py
                python: CPython 3.12.12
                root: /home/shuvrajeet/Documents/TensorflowAI/ReinforcementLearning/Vectorized/DoubleDQN/MountainCar
                startedAt: "2026-05-12T20:22:50.927312Z"
                writerId: 8pmiw73fjm4ea6g4q6diipip54xbvswt
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 49
                - 53
            "2":
                - 2
                - 3
                - 5
                - 49
                - 53
            "3":
                - 14
                - 17
                - 61
            "4": 3.12.12
            "5": 0.26.1
            "12": 0.26.1
            "13": linux-x86_64
batch_size:
    value: 512
buffer_size:
    value: 300000
epsilon_decay_steps:
    value: 800000
epsilon_end:
    value: 0.1
gamma:
    value: 0.98
lr:
    value: 0.00029579265019214325
target_update_freq:
    value: 5000
