import os

DATASET_PATHS = [
    "/home/shuvrajeet/Documents/Dataset/",
    "/mnt/storage/da24d402/Documents/Dataset/",
]
DATASET_PATH = next((path for path in DATASET_PATHS if os.path.isdir(path)), None)
print(f"Using dataset path: {DATASET_PATH}")

MODEL_NAME = "GLIDE"
SUPPORTED_DATASETS = ['coco', 'flickr30k']
DEFAULT_DATASET = "coco"
IMAGE_SIZE = (64, 64)
SUPER_RES_IMAGE_SIZE = (128, 128)
LATENT_IMAGE_SIZE = (16, 16)
BATCH_SIZE = 16
EPOCHS = 50
TEXT_VOCAB_SIZE = 8000
TEXT_SEQUENCE_LENGTH = 32
EMBED_DIM = 128
TIME_EMBED_DIM = 128
BASE_CHANNELS = 128
NUM_RES_BLOCKS = 2
LATENT_DIM = 128
DIFFUSION_STEPS = 300
SAMPLING_STEPS = 60
BETA_START = 1e-4
BETA_END = 0.02
GUIDANCE_DROPOUT = 0.1
GUIDANCE_SCALE = 3.0
USE_UNET_BACKBONE = True
USE_LEARNED_VARIANCE = False
USE_CLASSIFIER_FREE_GUIDANCE = True
USE_DDIM_SAMPLER = False
AUTOENCODER_LEARNING_RATE = 2e-4
DENOISER_LEARNING_RATE = 2e-4
TEXT_ENCODER_LEARNING_RATE = 2e-4
PRIOR_LEARNING_RATE = 2e-4
CONSISTENCY_LEARNING_RATE = 2e-4
ARRAY_CACHE_MODE = "memory"
DECODE_CACHE_MODE = "disk"
CACHE_DIR = "cache"
SHUFFLE_BUFFER_SIZE = 10000
ENABLE_DATASET_NONDETERMINISM = True
SAVE_EVERY_N_EPOCHS = 5
SAMPLE_EVERY_N_EPOCHS = 5
MAX_DATASET_ITEMS = None
