wandb_version: 1

batch_size:
  value: 256
buffer_size:
  value: 100000
epsilon_decay_steps:
  value: 800000
epsilon_end:
  value: 0.1
gamma:
  value: 0.98
lr:
  value: 4.716656986319817e-05
target_update_freq:
  value: 1000
