wandb_version: 1

batch_size:
  value: 128
buffer_size:
  value: 200000
epsilon_decay_steps:
  value: 1600000
epsilon_end:
  value: 0.05
gamma:
  value: 0.995
lr:
  value: 4.494879535217026e-05
target_update_freq:
  value: 2500
