wandb_version: 1

batch_size:
  value: 128
buffer_size:
  value: 300000
epsilon_decay_steps:
  value: 800000
epsilon_end:
  value: 0.02
gamma:
  value: 0.98
lr:
  value: 0.00023426049508523103
target_update_freq:
  value: 2500
