wandb_version: 1

batch_size:
  value: 256
buffer_size:
  value: 200000
epsilon_decay_steps:
  value: 1200000
epsilon_end:
  value: 0.1
gamma:
  value: 0.99
lr:
  value: 3.0065311487129063e-05
target_update_freq:
  value: 2500
