wandb_version: 1

batch_size:
  value: 512
buffer_size:
  value: 200000
epsilon_decay_steps:
  value: 1200000
epsilon_end:
  value: 0.1
gamma:
  value: 0.98
lr:
  value: 0.00023467143773815447
target_update_freq:
  value: 5000
