import os

DATASET_PATHS = ['/home/shuvrajeet/Documents/Dataset/', '/mnt/storage/da24d402/Documents/Dataset/']
DATASET_PATH = next((p for p in DATASET_PATHS if os.path.isdir(p)), None)
print(f"Using dataset path: {DATASET_PATH}")

HR_IMAGE_SIZE = (128, 128)
LR_IMAGE_SIZE = (32, 32)
UPSCALE_FACTOR = 4
BATCH_SIZE = 8
EPOCHS = 50
GENERATOR_LEARNING_RATE = 1e-4
DISCRIMINATOR_LEARNING_RATE = 1e-4
CONTENT_LOSS_WEIGHT = 1.0
ADVERSARIAL_LOSS_WEIGHT = 1e-3
SRGAN_NUM_RES_BLOCKS = 16
ARRAY_CACHE_MODE = "memory"
DECODE_CACHE_MODE = "disk"
CACHE_DIR = "cache"
SHUFFLE_BUFFER_SIZE = 10000
ENABLE_DATASET_NONDETERMINISM = True
SAVE_EVERY_N_EPOCHS = 5
SAMPLE_EVERY_N_EPOCHS = 5
