import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = "/home/shuvrajeet/Documents/Dataset/flickr30k"
COCO_DIR = "/home/shuvrajeet/Documents/Dataset/coco"

# Data
IMAGE_SIZE = (224, 224)
IMAGE_CHANNELS = 3
PIXEL_MAX_VALUE = 255.0
BATCH_SIZE = 64
VOCAB_SIZE = 10000
MAX_LENGTH = 40
VALIDATION_SPLIT = 0.1
SEED = 42
SHUFFLE_BUFFER = 8192
VOCAB_ADAPT_BATCH_SIZE = 1024
TOKEN_DROPOUT = 0.1

# Model
DECODER = "transformer"
RESNET_FILTERS = (64, 128, 256, 512)
RESNET_BLOCKS = (2, 2, 2, 2)
ENCODER_DIM = RESNET_FILTERS[-1]
TRANSFORMER_DIM = 512
TRANSFORMER_HEADS = 8
TRANSFORMER_FF_DIM = 1024
TRANSFORMER_LAYERS = 3
IMAGE_GRID_SIZE = (7, 7)
DROPOUT = 0.2

# Caption training
EPOCHS = 50
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-5
CLIP_NORM = 1.0
FREEZE_EPOCHS = 2
FINETUNE_LEARNING_RATE = 1e-4
LABEL_SMOOTHING = 0.1
EARLY_STOPPING_PATIENCE = 10
LR_PATIENCE = 3
LR_FACTOR = 0.5
MIN_LEARNING_RATE = 1e-6

# COCO image-caption contrastive pretraining
PRETRAIN_EPOCHS = 20
PRETRAIN_BATCH_SIZE = 64
PRETRAIN_LEARNING_RATE = 3e-4
PRETRAIN_WEIGHT_DECAY = 1e-4
PRETRAIN_TEMPERATURE = 0.07
PRETRAIN_RESIZE = (256, 256)
PRETRAIN_BRIGHTNESS = 0.3
PRETRAIN_CONTRAST = (0.6, 1.4)
PRETRAIN_SATURATION = (0.6, 1.4)
PROJECTION_HIDDEN_DIM = 256
PROJECTION_DIM = 128
CONTRASTIVE_VOCAB_SIZE = 20000
CONTRASTIVE_EMBEDDING_DIM = 256
CONTRASTIVE_TEXT_DIM = 512
COSINE_ALPHA = 0.01
PRETRAIN_CLIP_NORM = 1.0
PRETRAIN_CHECKPOINTS = 1
PRETRAIN_EARLY_STOPPING_PATIENCE = 12
PRETRAIN_EARLY_STOPPING_MIN_DELTA = 1e-4

# Evaluation and visualization
BLEU_EXAMPLES = 200
BLEU_MAX_ORDER = 4
PERPLEXITY_MAX_LOSS = 20
GRID_ROWS = 4
GRID_COLUMNS = 4
GRID_FIGSIZE = (16, 16)
GRID_CAPTION_WIDTH = 35
GRID_DPI = 120
GRID_CAPTION_Y = -0.06
GRID_FONT_SIZE = 8
BEAM_WIDTH = 3
BEAM_LENGTH_ALPHA = 0.6

# Distribution
MIN_GPUS = 2

# Output paths
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints")
LOG_DIR = os.path.join(BASE_DIR, "logs")
VOCABULARY_PATH = os.path.join(BASE_DIR, "vocabulary.json")
PRETRAINED_CNN_PATH = os.path.join(CHECKPOINT_DIR, "pretrain", "resnet18_encoder.weights.h5")
PRETRAIN_COMPLETE_PATH = os.path.join(CHECKPOINT_DIR, "pretrain", ".complete")
CONTRASTIVE_VOCABULARY_PATH = os.path.join(
    CHECKPOINT_DIR, "pretrain", "coco_vocabulary.json")
