

DATASET_ROOT = "/home/shuvrajeet/Documents/Dataset"
BATCH_SIZE = 64
MAX_LENGTH = 128
VOCAB_SIZE = 20000
VALIDATION_SPLIT = 0.1
LOWERCASE = True
SEED = 42

EPOCHS = 10
LEARNING_RATE = 1e-3
WEIGHT_DECAY = 0.0
GRADIENT_CLIP_NORM = 1.0

CHECKPOINT_DIR = "./checkpoints"
LOG_DIR = "./logs"
MIXED_PRECISION = False