import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = "/home/shuvrajeet/Documents/Dataset/flickr30k"

# Data
IMAGE_SIZE = (224, 224)
IMAGE_CHANNELS = 3
PIXEL_MAX_VALUE = 255.0
BATCH_SIZE = 128
VOCAB_SIZE = 15000
MAX_LENGTH = 40
VALIDATION_SPLIT = 0.1
SEED = 42
SHUFFLE_BUFFER = 8192
VOCAB_ADAPT_BATCH_SIZE = 1024

# Model
DECODER = "lstm"  # "lstm" or "gru"
CNN_FILTERS = (32, 64, 128, 256, 512)
CNN_KERNEL_SIZE = 3
CNN_STRIDE = 2
EMBEDDING_DIM = 256
HIDDEN_DIM = 512
DROPOUT = 0.3

# Caption training
EPOCHS = 50
LEARNING_RATE = 3e-4
WEIGHT_DECAY = 1e-5
CLIP_NORM = 1.0
FREEZE_EPOCHS = 5
FINETUNE_LEARNING_RATE = 1e-4
EARLY_STOPPING_PATIENCE = 7
LR_PATIENCE = 1
LR_FACTOR = 0.5
MIN_LEARNING_RATE = 1e-6

# SimCLR pretraining
PRETRAIN_EPOCHS = 100
PRETRAIN_BATCH_SIZE = 256
PRETRAIN_LEARNING_RATE = 1e-3
PRETRAIN_WEIGHT_DECAY = 1e-4
PRETRAIN_TEMPERATURE = 0.1
PRETRAIN_RESIZE = (256, 256)
PRETRAIN_BRIGHTNESS = 0.3
PRETRAIN_CONTRAST = (0.6, 1.4)
PRETRAIN_SATURATION = (0.6, 1.4)
PROJECTION_HIDDEN_DIM = 256
PROJECTION_DIM = 128
COSINE_ALPHA = 0.01
PRETRAIN_CLIP_NORM = 1.0
PRETRAIN_CHECKPOINTS = 1
PRETRAIN_EARLY_STOPPING_PATIENCE = 12
PRETRAIN_EARLY_STOPPING_MIN_DELTA = 1e-4

# Evaluation and visualization
BLEU_EXAMPLES = 1000
BLEU_MAX_ORDER = 4
PERPLEXITY_MAX_LOSS = 20
GRID_ROWS = 4
GRID_COLUMNS = 4
GRID_FIGSIZE = (16, 16)
GRID_CAPTION_WIDTH = 35
GRID_DPI = 120
GRID_CAPTION_Y = -0.06
GRID_FONT_SIZE = 8

# Distribution
MIN_GPUS = 2

# Output paths
CHECKPOINT_DIR = os.path.join(BASE_DIR, "checkpoints")
LOG_DIR = os.path.join(BASE_DIR, "logs")
VOCABULARY_PATH = os.path.join(BASE_DIR, "vocabulary.json")
PRETRAINED_CNN_PATH = os.path.join(CHECKPOINT_DIR, "pretrain", "cnn_encoder.weights.h5")
PRETRAIN_COMPLETE_PATH = os.path.join(CHECKPOINT_DIR, "pretrain", ".complete")
